### PR TITLE
line number now output when test fails

### LINKED ISSUE #4: JS: Show line information when a test fails at a todo or assignment failure
current output

```
❌ 
eyg/functions_test.call_generic_test: Error: This has not yet been implemented
```

### PR DESCRIPTION
**Pull request by ajstrand**
should resolve #4 

To test:

modify an existing gleeunit test like:
```gleam
pub fn example_mult_test() {
  assert 4 = 2 * 7
}
```

Then run `gleam test --target=javascript` in your terminal. 

Example terminal output when an error occurs: 

```bash
  Compiling gleam_stdlib
  Compiling gleeunit
   Compiled in 1.16s
    Running gleeunit_test.main
.F.......
Failures:

  1) another_test_module:example_mult_test/0
     Failure: #{function => <<"example_mult_test">>,gleam_error => assert,
                line => 6,message => <<"Assertion pattern match failed">>,
                module => <<"another_test_module">>,value => 14}
     Stacktrace:
       another_test_module.example_mult_test
     Output: 

Finished in 0.036 seconds
9 tests, 1 failures
```

### CODE REVIEW

**Comment by inoas** [comment]
What about adding the line number like so:
```
process.stdout.write(`\n❌ ${moduleName}.${fnName}:${error.line}: ${error}\n`);
```

File: src/gleeunit_ffi.mjs [hunk 1]
```diff
@@ -40,6 +40,8 @@ export async function main() {
         passes++;
       } catch (error) {
         let moduleName = "\n" + js_path.slice(0, -4);
+        const lineNumberInfo = `\nThe test failed at line ${error.line}\n`;
+        process.stdout.write(lineNumberInfo);
```
Comment (lpil) [inline src/gleeunit_ffi.mjs:44]: The error isn't guarenteed to have a line number on it, it could be a regular old JavaScript error. We'll need to check if so.

Let's use the format @inoas suggested, looks nice!

Could you copy/paste the output into the PR description or a comment? Bit easier for people to review. Thanks!

**Comment by ajstrand** [comment]
@lpil is there a desire to write a test that fails on purpose, so we explicitly test the error handling functionality?

Also since the test runner for JS is a custom test runner, would it be useful to look at test runners like Jest/Ava, so that folks dont have to write a bunch of functionality from scratch if they want to add features later?

**Comment by lpil** [comment]
> @lpil is there a desire to write a test that fails on purpose, so we explicitly test the error handling functionality?

I think best to just edit the tests to do whatever you want for now. In future when we have a less hacky test runner we'll have real tests about output formatting.

> Also since the test runner for JS is a custom test runner, would it be useful to look at test runners like Jest/Ava, so that folks dont have to write a bunch of functionality from scratch if they want to add features later?

We are not going to depend on npm in this package at all, but you could write a `gleam_ava` package etc. Would be cool!

**Review by lpil — APPROVED** [review]
Thanks!
